name: Deploy Multi docker
on:
  push:
    branches:
      - master
    tags:
      - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "====== Release ======"